### ISSUE TITLE
Installing modules

### ISSUE THREAD

**Issue by EugenTepin** [ExtendScript/extendscript-modules#1]
I have tried to install some modules like this:
`npm install @extendscript/aes.patch.bundle.array`
But i get "Not Found" error. What am i doing wrong?

**Comment by GitBruno** [comment]
Hey @EugenTepin, thanks for checking it out! I haven't published anything yet. I am on holidays at the moment and am planning on picking this up after when I'm back in July.

**Comment by GitBruno** [comment]
This works now!

    npm install @extendscript/aes.patch.bundle.array

Might it be good to add an NPM version badge?

https://github.com/ExtendScript/extendscript-modules/tree/master/aes/patch/bundle.array
